// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: This configuration file is not currently used by the application
// Prisma configuration is managed through schema.prisma
import "dotenv/config";

// Commented out due to type error - prisma/config module doesn't exist
// import { defineConfig, env } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: env("DATABASE_URL"),
//   },
// });
